name: portfolio-app
region: nyc
static_sites:
  - name: portfolio-react
    git:
      repo_clone_url: https://github.com/bensoer/project-portfolio.git
      branch: master
    build_command: "npm install && npm run build"
    source_dir: src
    output_dir: build
    environment_slug: "node-js"
domains:
  - domain: portfolio.bensoer.com
    type: PRIMARY
    wildcard: false